// examples/vite-vite/vite-remote/src/main.jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { AgGridDemo } from './AgGridDemo';
import App1 from './App1';
import { App2 } from './App2';

const root = ReactDOM.createRoot(document.getElementById('app'));
root.render(
  <React.StrictMode>
    <h1>MF Remote as standalone app</h1>

    <h2>App1</h2>
    <App1 />

    <h2>App2</h2>
    <App2 />

    <h2>AgGridDemo</h2>
    <AgGridDemo />

  </React.StrictMode>
);

// examples/vite-vite/vite-host/src/main.jsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './style.css';
import { createApp } from 'vue';
import VueHost from './VueHost.vue';

//@ts-ignore
const root = ReactDOM.createRoot(document.getElementById('app'));
root.render(
  <React.StrictMode>
    <h1>React host component</h1>
    <App />
  </React.StrictMode>
);

const vapp = createApp(VueHost)
vapp.mount('#vue-app')
